### ISSUE TITLE
Unable to make a group specification with doctrine association

### ISSUE THREAD

**Issue by codehead-pl** [K-Phoen/RulerZBundle#2]
I'm trying to create a specification to get the users within a certain usergroup. User entity has an association to Usergroup entity. My group spec:

``` php
<?php

namespace MyApp\UserBundle\Service;

use RulerZ\Spec\AbstractSpecification;

class GroupsSpec extends AbstractSpecification
{
    private $groups;

    public function __construct($groups)
    {
        $this->groups = $groups;
    }

    public function getRule()
    {
        return 'groups IN (:groups)';
    }

    public function getParameters()
    {
        return [
            'groups' => $this->groups
        ];
    }
}
```

This is how I use it

``` php
<?php

$this->rulerz->filterSpec($qb, new GroupsSpec($usergroups));
```

The issue I'm getting is:

```
[Semantical Error] line 0, col 65 near 'groups IN (:': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected.

SELECT u FROM MyApp\UserBundle\Entity\User u WHERE u.groups IN (:groups) 
```

Am I doing something wrong? It is a many-to-many relationship - does that change anything?

**Comment by K-Phoen** [comment]
I already tried to write a similar specification but the relationship was just a one-to-many (and it worked).
I'll try to reproduce the problem but I don't have much time right now, it would really be awesome if you could provide me a gist or something that I can execute and have the same error.

**Comment by codehead-pl** [comment]
This issue is Doctrine-related, because a simple select query with an IN where statement will break on many to many relation already. Maybe the mapping is wrong on our side. Closing the issue.
