### ISSUE TITLE
Incompatible with 0.19.3

### ISSUE THREAD

**Issue by yuriy-sorokin** [K-Phoen/RulerZBundle#9]
Hi, I've just updated my project, in which I use this bundle, and it become broken due to the fact that rulerz has recently updated to 0.19.3.

The issue is in that the file RulerZ\Compiler\EvalCompiler, mentioned in Resources/config/debug.yml, does not exist anymore

**Comment by K-Phoen** [comment]
Closing this issue since it has been fixed.
